---
- hosts: 10.73.38.117
  tasks:
   - name: Ping Windows Hosts
     win_ping:
   - name: Search-only, return list of found updates (if any), log to e:\ansible_search_wu.txt
     win_updates:
       category_names: 
         -SecurityUpdates
         -CriticalUpdates
         -UpdateRollups
       state: searched
       log_path: e:\ansible_search_wu.txt
   - name: Install all critical and security updates, log to e:\ansible_wu.txt
     win_updates:
       category_names: 
         -SecurityUpdates
         -CriticalUpdates
         -UpdateRollups
       state: installed
       log_path: e:\ansible_wu_log.txt
       register: update_result
       win_reboot:
           when: updateresult.reboot_required
           log_path: e:\ansible_search_wu.txt  
