---
- hosts: all
  gather_facts: no
  tasks:
  - name: Search-only, return list of found updates (if any), log to e:\ansible_search_wu.txt
     win_updates:
       category_names: 
         -SecurityUpdates
         -CriticalUpdates
         -UpdateRollups
       state: searched
       log_path: e:\ansible_search_wu.txt
       
   - name: Install all critical and security updates, log to e:\ansible_wu.txt
     win_updates:
       category_names: 
         -SecurityUpdates
         -CriticalUpdates
         -UpdateRollups
       log_path: e:\ansible_wu.txt
       state: installed
       reboot: yes 
